[package]
name = "covid-19-graphql"
version = "0.1.0"
authors = ["Patrick Coffey <patrickcoffey48@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
